# Generated by Django 3.2.9 on 2021-12-09 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxvtech', '0005_alter_feature_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_desc', models.CharField(max_length=100)),
                ('top_name', models.CharField(max_length=100)),
                ('top_job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='testimonialTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_desc1', models.CharField(max_length=100)),
                ('top_name2', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='pics/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
        ),
    ]
