# Generated by Django 3.2.9 on 2021-12-09 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxvtech', '0006_testimonials_testimonialtop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialtop',
            name='img',
            field=models.FileField(upload_to='pics/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'pjeg', 'pjp', 'doc', 'svg'])]),
        ),
    ]
